version: "3.8"

networks:
  backend-network:
  frontend-network:

secrets:
  mongo-database:
    file: envs/mongo-database.txt
  mongo-username:
    file: envs/mongo-username.txt
  mongo-password:
    file: envs/mongo-password.txt

services:

  app:
    container_name: app
    # Método #1 de hacer build (con la estructura del proyecto actual)
    # Este es posbile ya que dividimos en carpetas y cada carpeta tiene su
    # Dockerfile
    build: app
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./app/src:/src
    networks:
      - backend-network
      - frontend-network

  web:
    container_name: web
    # Método #2 de hacer build (con la estructura del proyecto actual)
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - frontend-network

  mongo-db:
    container_name: mongo-db
    image: mongo:5.0.3
    restart: always    
    ports:
      - 27017:27017
    volumes:
      - ./.dbdata:/data/db
    secrets:
      - mongo-database
      - mongo-username
      - mongo-password
    environment:
      MONGO_INITDB_DATABASE: /run/secrets/mongo-database
      MONGO_INITDB_ROOT_USERNAME: /run/secrets/mongo-username
      MONGO_INITDB_ROOT_PASSWORD: /run/secrets/mongo-password
    networks:
      - backend-network

  mongo-express: # Mongo-Express es una herramienta gráfica de administración de clientes web MongoDB.
    container_name: mongo-express
    image: mongo-express:0.54.0
    restart: always
    depends_on:
      - mongo-db
    ports:
      - 8081:8081
    secrets:
      - mongo-database
      - mongo-username
      - mongo-password
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-db
      ME_CONFIG_MONGODB_ADMINUSERNAME: /run/secrets/mongo-username
      ME_CONFIG_MONGODB_ADMINPASSWORD: /run/secrets/mongo-password
      # Es recomendable poner otro usuario y contraseña distintos al de admin
      # Pero por simplicidad se pondrán los mismos de la siguiente forma:
      ME_CONFIG_BASICAUTH_USERNAME: /run/secrets/mongo-username
      ME_CONFIG_BASICAUTH_PASSWORD: /run/secrets/mongo-password
    networks:
      - backend-network